version: '3.8'

services:
  api:
    ports:
      - "5688:5678"
    command: sh -c "pip install debugpy && python -m debugpy --listen 0.0.0.0:5678 --wait-for-client -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      - DEBUG=true
